server:
  port: 10000
spring:
  application:
    name: gateway-service
  profiles:
    #运行环境: dev|test|prod
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    gateway:
      #spring cloud gateway 全局跨域配置
      globalcors:
        add-to-simple-url-handler-mapping: on
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowCredentials: true
            allowedMethods: '*'
            allowedHeaders: '*'
            exposedHeaders: '*'
            max-age: 3600
