#日志配置
logging:
  file:
    path: d:/data/logs
    name: ${logging.file.path}/${spring.application.name}.log
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 20MB
      clean-history-on-start: on
eureka:
  server:
    #关闭自我保护
    enable-self-preservation: off
    eviction-interval-timer-in-ms: 10000
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka,http://127.0.0.1:10087/eureka,http://127.0.0.1:10088/eureka
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: on
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点设置为false；集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: on
    #去拉取服务的信息的时间间隔（默认30秒）
    registry-fetch-interval-seconds: 20
  instance:
    prefer-ip-address: on
    #每过60秒给注册中心发送心跳
    lease-renewal-interval-in-seconds: 60
    #超过120秒没发送心跳，让注册中心删除实例
    lease-expiration-duration-in-seconds: 120
