server:
  port: 8080
spring:
  application:
    name: stock-decrease
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.40.132:33306/ah_stock_decrease?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    database: 6
    host: 192.168.226.129
    port: 6379
    password: 123456
    client-name: stock_decrease_client
    # Redisson settings
    # Tips: Use Redisson through spring bean with RedissonClient interface or
    #       RedisTemplate/ReactiveRedisTemplate objects
    #path to config - redisson.yml
    redisson:
      file: classpath:redisson-single.yml
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka,http://127.0.0.1:10088/eureka
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: on
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
ribbon:
  eureka:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml,mapper/**/*Dao.xml
  type-aliases-package: com.**.domain,cn.**.domain,com.**.entity,cn.**.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID"
      id-type: auto
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# PageHelper分页插件
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
